# 帧参数
#sdsa
BLOCK_SIZE = 8 #每个块占的逻辑像素
FRAME_WIDTH = 1750 #正方形帧
FRAME_HEIGHT = 1750
FPS = 30 #帧率

# 接口约束
MAX_INPUT_BYTES = 10 * 1024 * 1024  # 10MB
LEADER_DURATION_SECONDS = 2



#定位图案
FINDER_SIZE = 7
ALIGN_SIZE = 5
SEPARATOR_WIDTH = 1

#网格参数
GRID_COLS = FRAME_WIDTH // BLOCK_SIZE #总共1920像素除8个像素一快
GRID_ROWS = FRAME_HEIGHT // BLOCK_SIZE

#二维码
QR_VERSION = 26
QR_BOX_SIZE = 10  # 略微缩小 QR，增加四周留白
QR_BORDER = 1

# 最大原始数据字节数（V26 L级 + Base64 实测）
MAX_RAW_BYTES = 1013
HEADER_SIZE = 10